### PR TITLE
Git1-Color Solution Ready

### PR DESCRIPTION
**Pull request by JamesOzenci**
Please check the color. Thank you

### CODE REVIEW

**Comment by CIOzenci** [comment]
I didn't like the color. Pick another one...

**Comment by JamesOzenci** [comment]
A different color is picked. Please see this color.

**Comment by CIOzenci** [comment]
Okay, this is good. I will close this Pull Request and see if I can still keep the code only in this branch without going into the ReleaseCandidate branch...

**Comment by CIOzenci** [comment]
Success. We have this approved and no code has been merged. I see this warning writing on Github:
Closed with unmerged commits. This pull request is closed but the Git1-Color branch has unmerged commits... I will now test reopening and see if I see if it gives me an option to merge inside the website, not that I need it, but just out of curiosity.

**Comment by CIOzenci** [comment]
Yes. It does show a button "Merge pull request". I am going to request personal account to merge it inside visual studio instead of using the website. Closing this Pull Request...

**Comment by JamesOzenci** [comment]
I've merged from "Git1-Color" into "ReleaseCandidate" branch using Visual Studio. This concludes this test under this issue...

**Pull request closed without merging**
